#!/usr/bin/expect -f
spawn telnet 172.17.8.212
set timeout 3
expect "Username:"
send "admin\r"
expect "Password:"
send "admin\r"
expect ">"
send "ena\r"
expect "password:"
send "admin\r"
expect "#"
send "show vlan id 2121\r"
expect "#"
set i 1
while {$i < 51} {
set output [open "show-vlan.txt" "w"]
set outcome $expect_out(buffer)
puts $output $outcome
incr i
}
close $output
expect "#"
send "exit\r"

